# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 21:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Краткое описание')),
                ('Краткое описание', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(db_index=True, default=0, verbose_name='Цена')),
                ('price_acc', models.FloatField(blank=True, null=True, verbose_name='Цена с учетом скидки')),
                ('in_stock', models.BooleanField(db_index=True, default=True, verbose_name='Есть в наличии')),
                ('is_new', models.BooleanField(db_index=True, default=False, verbose_name='Новый товар')),
                ('is_popular', models.BooleanField(db_index=True, default=False, verbose_name='Популярный')),
                ('rating', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Рейтинг')),
                ('image', models.ImageField(upload_to='items/list', verbose_name='Основное изображение')),
                ('item_type', models.CharField(choices=[('TO', 'Вершина'), ('NO', 'Узел'), ('LE', 'Лист')], default='TO', max_length=2, verbose_name='Тип')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.Item')),
            ],
        ),
    ]
