# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 21:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Краткое описание',
            new_name='Полное описание',
        ),
    ]
