# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-09 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20160907_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('TO', 'Вершина'), ('NO', 'Узел'), ('LE', 'Лист')], db_index=True, default='TO', max_length=2, verbose_name='Тип'),
        ),
    ]
