# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-03 21:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['parent', 'order', 'name'], 'verbose_name': 'подкатегория', 'verbose_name_plural': 'подкатегории'},
        ),
    ]
