# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-03 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='good',
            options={'ordering': ['category', 'is_new', 'price', 'name'], 'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
        migrations.AddField(
            model_name='good',
            name='rating',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='Рейтинг'),
        ),
    ]
